# Generated by Django 3.2.7 on 2021-09-10 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time_attention', models.DateTimeField()),
                ('end_time_attention', models.TimeField()),
                ('company', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('answer', models.TextField(blank=True)),
                ('application_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
